import { PaymentRowData } from '@/types';

export const SAMPLE_DATA: PaymentRowData[] = [
  {
    id: 1,
    name: '점심 토스트 (이삭토스트)',
    category: 'FOOD',
    payer: '철수',
    participants: ['동균', '철수', '영희'],
    date: new Date('2023/12/15'),
    totalAmount: 15300,
  },
  {
    id: 2,
    name: '탕후루 군것질',
    category: 'FOOD',
    payer: '동균',
    participants: ['동균', '철수'],
    date: new Date('2023/12/15'),
    totalAmount: 5000,
  },
  {
    id: 3,
    name: 'PC방',
    category: 'ACTIVITY',
    payer: '철수',
    participants: ['철수', '영호', '동균', '영희'],
    date: new Date('2023/12/15'),
    totalAmount: 12000,
  },
  {
    id: 4,
    name: '저녁 소고기 (황소고집)',
    category: 'FOOD',
    payer: '동균',
    participants: ['철수', '영호', '동균', '영희'],
    date: new Date('2023/12/15'),
    totalAmount: 88000,
  },
  {
    id: 5,
    name: '펜션',
    category: 'ACCOMMODATION',
    payer: '철수',
    participants: ['철수', '영호', '동균'],
    date: new Date('2023/12/15'),
    totalAmount: 12000,
  },
  {
    id: 6,
    name: '차량 렌트',
    category: 'TRANSPORTATION',
    payer: '동균',
    participants: ['철수', '영호', '동균', '영희'],
    date: new Date('2023/12/15'),
    totalAmount: 240000,
  },
  {
    id: 7,
    name: '아침 식사 (편의점)',
    category: 'FOOD',
    payer: '철수',
    participants: ['철수', '영호', '동균'],
    date: new Date('2023/12/16'),
    totalAmount: 6000,
  },
  {
    id: 8,
    name: 'PC방',
    category: 'ACTIVITY',
    payer: '동균',
    participants: ['철수', '동균'],
    date: new Date('2023/12/16'),
    totalAmount: 8000,
  },
];
